In [10]:
import numpy as np 
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[5,6,4],[1,2,3]])
x+y

array([[6, 8, 7],
       [5, 7, 9]])

In [11]:
alpha = 3
beta = 2
z = np.add(np.multiply(alpha,x),np.multiply(beta,y))
z


array([[13, 18, 17],
       [14, 19, 24]])

In [13]:
x.T@y

array([[ 9, 14, 16],
       [15, 22, 23],
       [21, 30, 30]])

## Normalising vectors : L2 norm (), L1 norm (Manhattan Norm), and max norm
- L2 norm is also known as Euclidean norm
- L1 norm is also known as Manhattan norm
- Max norm is also known as infinity norm

## Details on Norms
- L1 norm is used when the difference between the values is more important than the actual values
- Max norm is used when only the maximum value is important

## L2 norm (Euclidean norm)
- It is the most commonly used norm
- It is the square root of the sum of the squared vector values
- Example: L2 norm of [x,y,z] = sqrt(x^2 + y^2 + z^2)
- Implementation: norm(vector, 2)
  
## L1 norm (Manhattan norm)
- It is the sum of the absolute vector values
- Example: L1 norm of [x,y,z] = |x| + |y| + |z|
- Implementation: norm(vector, 1)
- It is used when the difference between the values is more important than the actual values

## Max norm (infinity norm)
- It is the maximum vector values
- Example: L1 norm of [x,y,z] = max(|x|, |y|, |z|)
- Implementation: norm(vector, inf)
- It is used when only the maximum value is important
- It is also used in neural networks
- 

In [24]:
#implementation of L2 norm
a = np.array([[3],[-4]])
b = np.array([[12],[-5]])
def L2_norm(x):
    return np.sqrt(np.sum(np.square(x)))
def L2_norm_alt(x):
    return np.linalg.norm(x,ord=2)

#implementation of L1 norm
def L1_norm(x):
    return np.sum(np.abs(x))
def L1_norm_alt(x):
    return np.linalg.norm(x,ord=1)

#Max norm (infinity norm)
def max_norm(x):
    return np.max(np.abs(x))
def max_norm_alt(x):
    return np.linalg.norm(x,ord=np.inf)

distance_x_y = L2_norm(x-y)
distance_x_y


7.745966692414834

In [35]:
cos_theta = (a.T@b)/(L2_norm(a)*L2_norm(b))
angle = np.arccos(cos_theta)
angle*180/np.pi
# cos_theta

array([[30.51023741]])